CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    email text NOT NULL CHECK (email <> ''),
    password text NOT NULL CHECK (password <> ''),
    status text NOT NULL
);

INSERT INTO users (name, email, password, status)
VALUES ('Keyvin Diaz', 'key.test@gmail.com', 'test12345', 'a');

INSERT INTO users (name, email, password, status)
VALUES ('Test', 'test@gmail.com', 'test12345', 'a');
